### ISSUE TITLE
How to understand the concept of channel before layernorm?

### ISSUE THREAD

**Issue by xyhe1996** [zkkli/RepQ-ViT#6]
Hi~ the concept of channel-wise in Conv is quite intuitive, but how to understand channel in tensor with shape [batch_size, num_seq, num_hidden] ?  weather the channel refers to the num_seq dim or not?

**Comment by zkkli** [comment]
Hi，
The channel dimension refers to the last dimension of the tensor, i.e., num_hidden.

**Comment by xyhe1996** [comment]
> Hi， The channel dimension refers to the last dimension of the tensor, i.e., num_hidden.

appreciate your quick reply. so take a tensor with shape (1, 197, 768) as an example，the x-axis of the boxplot figure in paper should have 768 xticks for 0~767 channel, the y-axis represents the value in each channel, and there are 197 values within each box for a  specific channel. am i right? if i miss something, pls let me know.

**Comment by zkkli** [comment]
Yeah, you're right.

**Comment by xyhe1996** [comment]
thx again for your help ~
