### ISSUE TITLE
What does reconstruction mean in quantization.

### ISSUE THREAD

**Issue by XA23i** [zkkli/RepQ-ViT#8]
Hi, I notice in Table 1.  there is "No REC" in column 3. And I wonder what it means and does it affects inference speed a lot. Thank you.

**Comment by zkkli** [comment]
Hi,

Reconstruction in this paper means whether or not reconstruction is needed in the process of obtaining a quantized model, e.g. layer-wise reconstruction or block-wise reconstruction.
The fact that RepQ-ViT does not require reconstruction means that the model quantization process can be accomplished more quickly. Reconstruction has no effect on the inference process.

**Comment by XA23i** [comment]
Thank you for your quick reply. I've got it now.
